module.exports = {
  user_created: "User created successfully",
  success: "Success",
  user_exists: "User already exists",
  un_success: "Unsuccessful",
  server_error: "Unable to connect to server!",
  user_not_found: "User not found!",
  invalid_password: "Invalid Password!",
  logged_in: "Logged In!",
  logged_out: "Logged Out!",
  no_token_provided: "No token provided!",
  unAuthorized: "Un Authorized!",
  invalid_token: "Invalid / Expired Token",
  access_denied: "Access Denied!",
  select_file: "You must select a file.",
  file_uploaded: "File has been uploaded.",
  error_uploading_image: "Error when trying upload images",
  upload_only_images: "Please upload only images.",
  not_found: "Not found",
  uploaded_to_firebase: "File uploaded to firebase storage",
  unable_upload_image_url: "Unable to upload image url to database",
  file_size_error: "File is too large. Maximum size is 2MB.",
  unknown_error: "An unknown error occurred.",
  file_upload_error:"An error occurred during the file upload.",
  file_buffer_undefined:"File buffer is undefined",
  file_deletion_failed:"File deletion failed",
};
